import React from 'react';
import { ShieldAlert, X, Scale, CheckCircle, ExternalLink, AlertTriangle } from 'lucide-react';

export function LegalDisclaimerModal({ isOpen, onClose }) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-fade-in">
      <div className="relative w-full max-w-2xl rounded-2xl border border-amber-500/30 bg-slate-900 p-6 shadow-2xl space-y-5">
        
        {/* Header */}
        <div className="flex items-start justify-between border-b border-slate-800 pb-4">
          <div className="flex items-center gap-3">
            <div className="rounded-xl bg-amber-500/15 p-2.5 text-amber-400 border border-amber-500/30">
              <Scale className="h-6 w-6" />
            </div>
            <div>
              <h2 className="text-lg font-serif font-bold text-white flex items-center gap-2">
                Legal Information & Compliance Disclaimer
              </h2>
              <p className="text-xs text-slate-400">
                NyayaAI (न्याय AI) • Indian Legal Technology & Research Architecture
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-800 hover:text-white transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content */}
        <div className="space-y-4 text-xs text-slate-300 leading-relaxed max-h-[60vh] overflow-y-auto pr-2">
          <div className="rounded-xl bg-amber-500/10 border border-amber-500/20 p-3.5 text-amber-200">
            <div className="flex items-center gap-2 font-semibold text-amber-300 mb-1">
              <AlertTriangle className="h-4 w-4" />
              <span>Not a Substitute for Qualified Legal Counsel</span>
            </div>
            <p className="text-[11px] text-amber-200/90 leading-relaxed">
              NyayaAI is an advanced legal intelligence and document analysis system engineered to augment advocates, legal counsels, corporate compliance teams, and legal scholars in statutory research and clause risk analysis.
            </p>
          </div>

          <div className="space-y-3">
            <h4 className="font-semibold text-slate-100 flex items-center gap-1.5 text-xs">
              <CheckCircle className="h-3.5 w-3.5 text-emerald-400" />
              1. Bar Council of India & Advocates Act, 1961 Compliance
            </h4>
            <p className="text-slate-400">
              In accordance with the Advocates Act, 1961 and Bar Council of India rules, the outputs, summaries, risk scorings, and chatbot responses generated by NyayaAI do not constitute formal attorney-client legal advice, judicial certification, or solicitation of legal work.
            </p>

            <h4 className="font-semibold text-slate-100 flex items-center gap-1.5 text-xs">
              <CheckCircle className="h-3.5 w-3.5 text-emerald-400" />
              2. Statutory Grounding & Bare Act Verification
            </h4>
            <p className="text-slate-400">
              All citations provided (including Bharatiya Nyaya Sanhita 2023, Indian Contract Act 1872, Arbitration and Conciliation Act 1996, and Supreme Court of India precedents) are indexed from verified public legal repositories. Users are advised to review original High Court / Supreme Court law reports before filing judicial pleadings.
            </p>

            <h4 className="font-semibold text-slate-100 flex items-center gap-1.5 text-xs">
              <CheckCircle className="h-3.5 w-3.5 text-emerald-400" />
              3. Data Confidentiality & Privileged Information
            </h4>
            <p className="text-slate-400">
              Documents uploaded to NyayaAI are processed in an isolated sandbox environment designed to preserve litigation privilege and confidentiality in compliance with Section 126 of the Indian Evidence Act, 1872 / Section 132 of the Bharatiya Sakshya Adhiniyam, 2023.
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between border-t border-slate-800 pt-4">
          <span className="text-[11px] text-slate-400">
            Regulated under Indian Jurisprudence Standards
          </span>
          <button
            onClick={onClose}
            className="rounded-lg bg-amber-500 px-5 py-2 text-xs font-semibold text-slate-950 hover:bg-amber-400 transition-colors shadow-md shadow-amber-500/20"
          >
            I Acknowledge & Understand
          </button>
        </div>

      </div>
    </div>
  );
}
