import React, { useState } from 'react';
import { 
  FileText, 
  X, 
  Download, 
  Printer, 
  Copy, 
  Check, 
  Scale, 
  CheckCircle2, 
  Sparkles,
  ShieldCheck
} from 'lucide-react';
import confetti from 'canvas-confetti';

export function ExportMemoModal({ isOpen, onClose, document }) {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !document) return null;

  const handlePrint = () => {
    try {
      confetti({
        particleCount: 50,
        spread: 70,
        origin: { y: 0.5 }
      });
    } catch (e) {}
    window.print();
  };

  const handleCopyMarkdown = () => {
    const memoContent = `# LEGAL OPINION & STATUTORY RISK AUDIT MEMO
**Document**: ${document.title}
**Date**: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
**Jurisdiction**: ${document.jurisdiction}
**Governing Law**: ${document.governingLaw}
**Evidence Grounding Score**: ${document.groundingConfidence}%

---

## 1. EXECUTIVE SUMMARY
${document.summary.executiveSummary}

## 2. PROCEDURAL POSTURE
${document.summary.proceduralPosture}

## 3. CRITICAL RISK FINDINGS
${document.summary.keyRiskFindings.map((f, i) => `${i + 1}. ${f}`).join('\n')}

## 4. COUNSEL RECOMMENDATIONS
${document.summary.legalRecommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

## 5. CLAUSE RISK MATRIX & STATUTORY REDLINES
${document.clauseRisks.map((c) => `### ${c.clauseName} (${c.riskLevel} RISK)
- **Current Offending Text**: "${c.offendingText}"
- **Recommended Redline**: "${c.suggestedRedline}"
- **Statutory Grounding**: ${c.legalGrounding}`).join('\n\n')}

---
*Generated by NyayaAI Indian Legal Intelligence Platform*`;

    navigator.clipboard.writeText(memoContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/85 backdrop-blur-md animate-fade-in no-print">
      <div className="relative w-full max-w-3xl rounded-2xl border border-slate-800 bg-slate-900 shadow-2xl flex flex-col max-h-[90vh] overflow-hidden">
        
        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-slate-800 bg-slate-950 px-6 py-4">
          <div className="flex items-center gap-2.5">
            <div className="rounded-xl bg-amber-500/15 p-2 text-amber-400 border border-amber-500/30">
              <FileText className="h-5 w-5" />
            </div>
            <div>
              <h2 className="text-base font-serif font-bold text-white">
                Export AI Legal Opinion & Risk Audit
              </h2>
              <p className="text-xs text-slate-400">
                Formal legal memo formatted for advocate chamber review & corporate circulation
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1.5 rounded-lg border border-slate-800 bg-slate-900 px-3 py-1.5 text-xs text-slate-300 hover:border-slate-700 hover:text-white transition-colors"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5 text-amber-400" />}
              <span>{copied ? 'Copied MD' : 'Copy Text'}</span>
            </button>
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 rounded-lg bg-gradient-to-r from-amber-500 to-amber-600 px-4 py-1.5 text-xs font-bold text-slate-950 hover:from-amber-400 transition-all shadow-md"
            >
              <Printer className="h-3.5 w-3.5" />
              <span>Print / Save PDF</span>
            </button>
            <button
              onClick={onClose}
              className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-800 hover:text-white transition-colors ml-1"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Formatted Legal Memo Sheet Preview */}
        <div className="flex-1 overflow-y-auto p-6 sm:p-8 bg-slate-950">
          <div className="rounded-xl bg-[#FAF9F6] text-slate-900 p-8 sm:p-10 shadow-2xl border border-amber-900/10 space-y-6 font-serif">
            
            {/* Chamber Header */}
            <div className="border-b-2 border-slate-900 pb-4 text-center space-y-1">
              <div className="flex items-center justify-center gap-2 text-amber-700">
                <Scale className="h-6 w-6" />
              </div>
              <h1 className="text-xl font-bold tracking-wider uppercase font-serif text-slate-900">
                LEGAL OPINION & STATUTORY RISK AUDIT
              </h1>
              <p className="text-xs text-slate-600 font-sans tracking-wide">
                NYAYAAI LEGAL INTELLIGENCE PROTOCOL • BHARAT JURISPRUDENCE
              </p>
            </div>

            {/* Meta Grid */}
            <div className="grid grid-cols-2 gap-4 text-xs font-sans border-b border-slate-300 pb-4">
              <div>
                <span className="text-slate-500 font-semibold">CASE / MATTER:</span>
                <div className="font-bold text-slate-900">{document.title}</div>
              </div>
              <div>
                <span className="text-slate-500 font-semibold">DATE OF AUDIT:</span>
                <div className="font-bold text-slate-900">
                  {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
                </div>
              </div>
              <div>
                <span className="text-slate-500 font-semibold">GOVERNING LAW:</span>
                <div className="font-medium text-slate-800">{document.governingLaw}</div>
              </div>
              <div>
                <span className="text-slate-500 font-semibold">STATUTORY GROUNDING:</span>
                <div className="font-bold text-emerald-700">{document.groundingConfidence}% Verified</div>
              </div>
            </div>

            {/* 1. Executive Summary */}
            <div className="space-y-2 text-xs leading-relaxed">
              <h2 className="font-bold uppercase tracking-wider text-slate-900 border-b border-slate-200 pb-1 font-sans text-[11px]">
                1. EXECUTIVE LEGAL SUMMARY
              </h2>
              <p className="text-slate-800 leading-relaxed font-serif text-[13px]">
                {document.summary.executiveSummary}
              </p>
            </div>

            {/* 2. Key Risks */}
            <div className="space-y-2 text-xs">
              <h2 className="font-bold uppercase tracking-wider text-slate-900 border-b border-slate-200 pb-1 font-sans text-[11px]">
                2. PRIMARY STATUTORY VULNERABILITIES
              </h2>
              <div className="space-y-1.5">
                {document.summary.keyRiskFindings.map((finding, idx) => (
                  <div key={idx} className="flex items-start gap-2">
                    <span className="font-bold text-rose-800">{idx + 1}.</span>
                    <span className="text-slate-800 leading-relaxed">{finding}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* 3. Clause Redlines */}
            <div className="space-y-3 text-xs">
              <h2 className="font-bold uppercase tracking-wider text-slate-900 border-b border-slate-200 pb-1 font-sans text-[11px]">
                3. STATUTORY REDLINES & SUPREME COURT PRECEDENT DOCTRINES
              </h2>
              <div className="space-y-3">
                {document.clauseRisks.map((c) => (
                  <div key={c.id} className="p-3 bg-amber-50/70 rounded-lg border border-amber-200/80 space-y-1.5 font-sans">
                    <div className="font-bold text-slate-900 text-xs flex items-center justify-between">
                      <span>{c.clauseName}</span>
                      <span className="text-[10px] text-rose-700 uppercase font-bold">{c.riskLevel} RISK</span>
                    </div>
                    <div className="text-[11px] text-slate-700">
                      <strong>Recommended Redline:</strong> <span className="font-mono text-emerald-800">{c.suggestedRedline}</span>
                    </div>
                    <div className="text-[10px] text-slate-600 italic">
                      Authority: {c.legalGrounding}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Certification Footer */}
            <div className="border-t border-slate-400 pt-6 mt-6 flex justify-between items-end text-[10px] font-sans text-slate-500">
              <div>
                <p>Generated for legal counsel research pursuant to Advocates Act norms.</p>
                <p className="mt-0.5">NyayaAI • Indian Jurisprudence Engine v2.0</p>
              </div>
              <div className="text-right">
                <div className="font-serif font-bold text-slate-900 text-xs">NyayaAI Legal Intelligence Seal</div>
                <p>Evidence Grounded Verification</p>
              </div>
            </div>

          </div>
        </div>

      </div>
    </div>
  );
}
